### ISSUE TITLE
Freeze screen

### ISSUE THREAD

**Issue by kozhinas** [ezranbayantemur/react-native-rtmp-publisher#37]
### Describe the bug

hello, when I start the stream it shows 1 frame and the picture freezes, tell me what could be the problem?

### To Reproduce

Example screen

### Expected behavior

Not freezee

### Version

Last

### Smartphone info.

iOS 16.1.1

**Comment by ezranbayantemur** [comment]
Can you provide a code sample?
Did you compare your code with the example project?

**Comment by kozhinas** [comment]
I'm too lazy to send an example because I'm already using another library

**Comment by harrymelka** [comment]
> I'm too lazy to send an example because I'm already using another library

Hey, what library are you using ? 

thanks
