### ISSUE TITLE
Unable to build release version with react native 0.70.6

### ISSUE THREAD

**Issue by rranjan14** [ezranbayantemur/react-native-rtmp-publisher#8]
**Describe the bug**
While trying to build the release version of the android app, following error occurs:
```
* What went wrong:
Execution failed for task ':react-native-rtmp-publisher:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:<path_to_project>/node_modules/react-native-rtmp-publisher/android/build/intermediates/merged_res/release/values/values.xml:2729: AAPT: error: resource android:attr/lStar not found.
```

**To Reproduce**
1. Create a project with latest react native version
2. Install and setup `react-native-rtmp-publisher`
3. Navigate to android folder and run `./gradlew assembleRelease`

**Expected behavior**
Release variant of the `.apk` should have been built successfully

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1
 - React Native version 0.70.6
 - react-native-rtmp-publisher version 0.4.4

**Comment by ezranbayantemur** [comment]
Hello @rranjan14,
It should be fixed at [0.4.6](https://github.com/ezranbayantemur/react-native-rtmp-publisher/releases/tag/v0.4.6). Can you update and try it again?
PS: Android permission section is updated too, you should check that section after update
